
stages:
  - build
  - test
  - deploy


build-job:
  stage: build
  tags:
    - g5
  before_script:
    - echo "Docker Login to registery"
    - docker login --username $HUB_USER --password $HUB_PASS https://$HUB_URL
  script:
    - echo "build image"
    - docker build -t $HUB_URL/g5/dev_frontend:latest .
    - docker tag $HUB_URL/g5/dev_frontend:latest $HUB_URL/g5/frontend:$CI_COMMIT_SHORT_SHA
    - echo "push images"
    - docker push $HUB_URL/g5/frontend:$CI_COMMIT_SHORT_SHA 
    - docker push $HUB_URL/g5/dev_frontend:latest


test-job:
  stage: test
  tags:
    - g5
  script:
    - echo "test stage devops"
    - date

deploy-job:
  stage: deploy
  trigger:
    project: amirbahador/devops
    branch: master