
stages:
  - build
  - test
  - deploy


build-job:
  stage: build
  tags:
    - g5
  script:
    - echo "build stage devops"
    - date


test-job:
  stage: test
  tags:
    - g5
  script:
    - echo "test stage devops"
    - date

deploy-job:
  stage: deploy
  tags:
    - g5
  script:
    - echo "deploy stage devops"
    - date